### ISSUE TITLE
Errores en módulos

### ISSUE THREAD

**Issue by sebatista** [ingadhoc/docker-odoo-adhoc#18]
Hola,
Modifiqué el archivo .env en mi filesystem local, indicando la versión 11.0 de odoo.
Al levantar los containers me indica los siguientes errores: 
CRITICAL ? odoo.modules.module: Couldn't load module server_mode
CRITICAL ? odoo.modules.module: No module named 'server_mode'
ERROR ? odoo.service.server: Failed to load server-wide module `server_mode`.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 867, in load_server_wide_modules odoo.modules.module.load_openerp_module(m)
File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 368, in load_openerp_module __import__('odoo.addons.' + module_name)
File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 61, in load_module f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
File "/usr/lib/python3.6/imp.py", line 297, in find_module raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'server_mode'

Lo mismo para database tools.
Será necesario modificar algo en odoo.conf???

Si necesitan mas información, me indican como. 

Desde ya muchas gracias.

**Comment by jjscarafia** [comment]
Buenas Seba, lamentablemente todavía no tenemos imagen funcionando para v11. Es decir, tenemos una pero con el repo enterprise de odoo y no la podemos publicar, tenemos que contrsuir una community pero nos falta tiempo. en cuanto podamos vamos a tratar de hacer una y documentar el uso. Lo lamento.
Me suena que Jorge Obiols publicó alguna en los grupos de odoo argentina
